import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import headshot from '../public/headshot-square.PNG';

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>

        <Image
          src={headshot}
          alt="Picture of the author"
          width={500}
          height={500}
          className="rounded-full border-4 border-white hover:scale-[1.03] duration-500"
        />

        <div className={styles.grid}></div>
      </main>
    </>
  );
}
